Migration table created successfully.
2014_10_12_000000_create_users_table: create table `users` (`id` bigint unsigned not null auto_increment primary key, `_id` char(36) not null, `full_name` varchar(255) null, `service_number` varchar(50) null, `rank` varchar(50) not null, `email` varchar(255) not null, `phone` varchar(255) null, `username` varchar(255) null, `role` varchar(255) null, `email_verified_at` datetime null, `permission_group_id` int null, `password` varchar(255) not null, `status` tinyint not null default '0', `created_by` bigint unsigned null, `remember_token` varchar(255) null, `remember_token` varchar(100) null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
2014_10_12_000000_create_users_table: alter table `users` add index `users__id_index`(`_id`)
2014_10_12_000000_create_users_table: alter table `users` add unique `users_email_unique`(`email`)
2014_10_12_100000_create_password_resets_table: create table `password_resets` (`email` varchar(255) not null, `token` varchar(255) not null, `created_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
2014_10_12_100000_create_password_resets_table: alter table `password_resets` add index `password_resets_email_index`(`email`)
2019_08_19_000000_create_failed_jobs_table: create table `failed_jobs` (`id` bigint unsigned not null auto_increment primary key, `uuid` varchar(255) not null, `connection` text not null, `queue` text not null, `payload` longtext not null, `exception` longtext not null, `failed_at` timestamp default CURRENT_TIMESTAMP not null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
2019_08_19_000000_create_failed_jobs_table: alter table `failed_jobs` add unique `failed_jobs_uuid_unique`(`uuid`)
2019_12_14_000001_create_personal_access_tokens_table: create table `personal_access_tokens` (`id` bigint unsigned not null auto_increment primary key, `tokenable_type` varchar(255) not null, `tokenable_id` bigint unsigned not null, `name` varchar(255) not null, `token` varchar(64) not null, `abilities` text null, `last_used_at` timestamp null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
2019_12_14_000001_create_personal_access_tokens_table: alter table `personal_access_tokens` add index `personal_access_tokens_tokenable_type_tokenable_id_index`(`tokenable_type`, `tokenable_id`)
2019_12_14_000001_create_personal_access_tokens_table: alter table `personal_access_tokens` add unique `personal_access_tokens_token_unique`(`token`)
CreatePermissionGroupsTable: create table `permission_groups` (`id` bigint unsigned not null auto_increment primary key, `_id` char(36) not null, `name` varchar(255) not null, `slug` varchar(255) null, `description` text null, `permissions` longtext null, `user_id` int not null, `is_default` tinyint not null default '0', `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
2022_04_14_093013_create_notifications_table: create table `notifications` (`id` char(36) not null, `type` varchar(255) not null, `notifiable_type` varchar(255) not null, `notifiable_id` bigint unsigned not null, `data` text not null, `read_at` timestamp null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
2022_04_14_093013_create_notifications_table: alter table `notifications` add index `notifications_notifiable_type_notifiable_id_index`(`notifiable_type`, `notifiable_id`)
2022_04_14_093013_create_notifications_table: alter table `notifications` add primary key `notifications_id_primary`(`id`)
2022_04_19_092633_create_log_types_table: create table `log_types` (`id` bigint unsigned not null auto_increment primary key, `title` varchar(255) not null, `slug` varchar(255) not null, `description` text not null, `user_id` int not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
2022_04_19_093407_create_logs_table: create table `logs` (`id` bigint unsigned not null auto_increment primary key, `log_type_id` int not null, `user_id` int not null, `message` text null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
2022_04_20_060741_create_properties_table: create table `properties` (`id` bigint unsigned not null auto_increment primary key, `_id` char(36) not null, `name` varchar(255) not null, `slug` varchar(255) not null, `description` text null, `user_id` int not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
2022_04_20_080753_create_property_models_table: create table `property_models` (`id` bigint unsigned not null auto_increment primary key, `property_id` bigint unsigned not null, `_id` char(36) not null, `name` varchar(255) not null, `description` text null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
2022_04_22_085534_create_suppliers_table: create table `suppliers` (`id` bigint unsigned not null auto_increment primary key, `_id` char(36) not null, `name` varchar(255) not null, `email` varchar(255) not null, `phone` varchar(255) null, `location` varchar(255) null, `address` text null, `user_id` int null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
2022_04_25_124833_create_categories_table: create table `categories` (`id` bigint unsigned not null auto_increment primary key, `_id` char(36) not null, `name` varchar(255) not null, `slug` varchar(255) not null, `user_id` bigint unsigned not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
2022_04_25_133219_create_locations_table: create table `locations` (`id` bigint unsigned not null auto_increment primary key, `_id` char(36) not null, `name` varchar(255) not null, `slug` varchar(255) not null, `user_id` bigint unsigned not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
2022_04_25_134953_create_departments_table: create table `departments` (`id` bigint unsigned not null auto_increment primary key, `_id` char(36) not null, `name` varchar(255) not null, `slug` varchar(255) not null, `user_id` int not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
2022_04_28_080701_create_spare_parts_table: create table `spare_parts` (`id` bigint unsigned not null auto_increment primary key, `part_number` varchar(255) not null, `serial_number` varchar(255) null, `description` text null, `unit_of_account` varchar(255) not null, `department_id` bigint unsigned null, `supplier_id` bigint unsigned null, `location_id` bigint unsigned null, `category_id` bigint unsigned null, `warranty_date` datetime null, `expiry_date` datetime null, `reorder_level` int null, `remarks` varchar(255) null, `control_level` int not null, `quantity` double not null default '0', `status` tinyint not null default '0', `user_id` bigint unsigned not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
2022_05_12_071444_update_spare_parts_add_property_model_id: alter table `spare_parts` add `property_model_id` bigint unsigned not null
2022_05_16_084116_create_lpos_table: create table `lpos` (`id` bigint unsigned not null auto_increment primary key, `number` varchar(255) not null, `quantity` double null, `supplier_id` bigint unsigned null, `delivery_date` datetime null, `user_id` bigint unsigned not null, `status` tinyint not null default '0', `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
2022_06_07_072525_create_stores_table: create table `stores` (`id` bigint unsigned not null auto_increment primary key, `name` varchar(255) not null, `slug` varchar(255) not null, `user_id` bigint unsigned not null, `status` tinyint unsigned not null default '1', `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
2022_06_07_074139_update_spare_parts_table_add_store_id: alter table `spare_parts` add `store_id` bigint unsigned not null
2022_06_14_122150_update_users_table_add_store_id: alter table `users` add `store_id` bigint unsigned null
2022_06_14_210649_create_stocks_table: create table `stocks` (`id` bigint unsigned not null auto_increment primary key, `spare_part_id` bigint unsigned not null, `quantity` int unsigned not null default '0', `entry_type` enum('IV', 'RV') not null default 'RV', `reference` varchar(255) null, `reason` varchar(255) null, `issue_status` tinyint unsigned not null default '0', `receive_status` tinyint unsigned not null default '0', `issue_type` enum('NML', 'TL') not null default 'NML', `voucher` varchar(255) null, `account_issued` enum('store', 'technician', 'supplier') not null default 'store', `issued_by` bigint unsigned null, `issued_to` int unsigned null, `date` datetime null, `received_by` bigint unsigned null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
2022_06_16_082750_update_stocks_table_add_fields: alter table `stocks` add `aircraft_id` bigint unsigned null, add `user_id` bigint unsigned null
2022_06_17_075530_create_aircraft_table: create table `aircraft` (`id` bigint unsigned not null auto_increment primary key, `property_model_id` bigint unsigned not null, `user_id` bigint unsigned not null, `tail_number` varchar(255) not null, `model` varchar(255) null, `serial_number` varchar(255) null, `engine_model` varchar(255) null, `status` tinyint unsigned not null default '1', `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
2022_06_21_131957_update_stocks_table_add_remarks: alter table `stocks` add `remarks` text null
2022_07_28_130149_update_spare_parts_table_add_svc_and_unsv: alter table `spare_parts` add `svc_quantity` double not null default '0' after `quantity`, add `unsvc_quantity` double not null default '0' after `svc_quantity`
2022_07_28_130300_update_stocks_table_add_state_column: alter table `stocks` add `state` enum('serviceable', 'unserviceable') not null default 'serviceable'
2022_08_04_122246_update_stocks_table_add_lpo_id: alter table `stocks` add `lpo_id` int unsigned null
2022_08_05_075020_update_lpos_table_add_lpo_date: alter table `lpos` add `date` date null
2022_08_20_145729_update_stocks_table_add_store_id: alter table `stocks` add `store_id` int unsigned null, add `record_of_voucher_id` int unsigned null
2022_08_21_081414_create_record_of_vouchers_table: create table `record_of_vouchers` (`id` bigint unsigned not null auto_increment primary key, `user_id` bigint unsigned not null, `vnumber` int unsigned not null, `entry_type` enum('rvstore', 'ivstore', 'ivtech', 'rvtech', 'rv', 'iv') not null, `store_id` bigint unsigned null, `supplier_id` bigint unsigned null, `aircraft_id` bigint unsigned null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
2022_08_29_075138_create_stock_record_sheets_table: create table `stock_record_sheets` (`id` bigint unsigned not null auto_increment primary key, `stock_id` int not null, `user_id` int not null, `balance_in_stock` int not null, `quantity` int not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
2022_08_31_030553_update_stocks_table_add_supplier_id: alter table `stocks` add `supplier_id` bigint unsigned null
2022_09_19_200141_update_permission_groups_table_add_menu_item_permissions: alter table `permission_groups` add `menu_item_permissions` longtext null
2022_12_05_081526_update_record_of_vouchers_table_add_technician_id: alter table `record_of_vouchers` add `technician_id` bigint unsigned null
2022_12_09_074326_update_lpos_table_add_reference: alter table `lpos` add `reference` text null
2022_12_09_074326_update_lpos_table_add_reference: alter table `lpos` drop `quantity`
Illuminate\Database\Migrations\Migration@anonymous\/var/www/html/kaca/database/migrations/2022_12_09_084105_update_users_table_add_department_id.php:7$ff: failed to dump queries. This may be due to changing database columns using Doctrine, which is not supported while pretending to run migrations.
2023_01_06_082029_update_lpos_table_add_type: alter table `lpos` add `type` enum('lpo', 'overseas') not null default 'lpo'
2023_01_19_075212_update_stocks_table_add_department_id: alter table `stocks` add `department_id` bigint unsigned null, add `quantity_requested` double not null default '0'
